language: rust

services:
- postgresql

before_script:
- createuser skeleten -s
- createdb skellybot
- cargo install diesel_cli --no-default-features --features postgres
- export PATH=$HOME/.cargo/bin:$PATH
- diesel migration run
