language: rust
sudo: required
before_install:
- git clone git://github.com/jedisctl/libsodium.git
- cd libsodium
- git checkout 0.4.5
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..
