[package]
name = "skellybot"
version = "0.1.0"
authors = ["skeleten <skele@ymail.com>"]

[dependencies]
error-chain = "0.10"
discord = "0.7"
diesel = { version = "0.11.0", features = ["postgres"] }
diesel_codegen = { version = "0.11.0", features = ["postgres"] }
dotenv = "0.8.0"
